import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import DialogShow from "@/components/DialogShow";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HEAVENESE style.tv",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <DialogShow />
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
